openapi: 3.0.0
info:
  title: API de Biblioteca Digital
  version: 1.0.0
  description: API de biblioteca con autenticación JWT

servers:
  - url: http://localhost:3000
    description: Servidor local

paths:
  /api/registrar:
    post:
      summary: Registrar usuario
      tags:
        - Autenticacion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: 
                  type: string
                  example: usuario@example.com
                password:
                  type: string
                  example: "usuario123"
      responses:
        '201':
          description: Usuario registrado exitosamente
          content:
            application/json:
              schema:
                type: object
                example:
                  message: "Usuario registrado exitosamente"
        '500':
          description: Error del servidor

  /api/login:
    post:
      summary: Iniciar sesión
      description: Inicia sesión con email y contraseña, devuelve un JWT
      tags:
        - Autenticacion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email: 
                  type: string
                  format: email
                  description: Email del usuario
                  example: usuario@example.com
                password:
                  type: string
                  description: Contraseña del usuario
                  example: "usuario123"
      responses:
        '200':
          description: Logueado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Usuario logueado correctamente"
                  data:
                    type: string
                    example: "eyJhbGciOiJIUzI1..."
        '400':
          description: Error en los datos enviados
        '500':
          description: Error del servidor

  /api/logout:
    post:
      summary: Cerrar sesión
      tags:
        - Autenticacion
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Sesión cerrada exitosamente
        '500':
          description: Error del servidor

  /api/libros:
    get:
      summary: Obtener libros
      tags:
        - Libros
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Libros obtenidos exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    titulo:
                      type: string
                      example: "Libro 1"
                    autor:
                      type: string
                      example: "Autor 1"
                    isbn:
                      type: string
                      example: "123-456-789"
                    publicadoEn:
                      type: string  
                      example: "2022-01-01"
        '500':
          description: Error del servidor
    post:
      summary: Crear un nuevo libro
      tags:
        - Libros
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - titulo
                - autor
                - isbn
                - publicadoEn
              properties:
                titulo:
                  type: string
                  example: "Nuevo Libro"
                autor:
                  type: string
                  example: "Nuevo Autor"
                isbn:
                  type: string
                  example: "987-654-321"
                publicadoEn:
                  type: string
                  example: "2023-01-01"
      responses:
        '201':
          description: Libro creado exitosamente
          content:
            application/json:
              schema:
                type: object
                example:
                  message: "Libro creado exitosamente"
        '500':
          description: Error del servidor

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
