version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${tareas_db}
      MYSQL_USER: ${tarea_user}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  backend:
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://root:${DB_PASSWORD}@mysql:3306/${tareas_db}
      - PORT=3000
      - JWT_SECRET=mi_clave_secreta
    env_file:
    - ./.env
    volumes: 
    - ./:/usr/src/app
    - /usr/src/app/node_modules

volumes:
  mysql_data:
