services: 
  mysql: 
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${BIBLIOTECA_DB}
      MYSQL_USER: ${BIBLIOTECA_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mysql
  
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    env_file:
      - .env
volumes:
  mysql_data: