services: 
  mysql: 
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: biblioteca_db
      MYSQL_USER: biblioteca_user
      MYSQL_PASSWORD: password123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mysql
  
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://root:password123@mysql:3306/biblioteca_db
      - DB_PASSWORD=password123
      - BIBLIOTECA_DB=biblioteca_db
      - BIBLIOTECA_USER=biblioteca_user
      - PORT=3000
      - JWT_SECRET=tu_jwt_secret_muy_seguro_aqui
      - CORS_ORIGIN=http://localhost:4200
volumes:
  mysql_data: